### ISSUE TITLE
help

### ISSUE THREAD

**Issue by rroarings** [ArielSaldana/Palringo-Bot-Engine#1]
how tf do i build this in visual studio mate and is it like the adbot or wat

**Comment by ArielSaldana** [comment]
@ValorPS Download visual studio 2014/15 and run PalringoBotEngine.sln and compile. And the bot connects to the palringo protocol and actively _speaks_ to it. The bot can be extended to be an ad bot yes, but by default that functionality is not built in for obvious reasons. ;)

**Comment by rroarings** [comment]
bro ariel plz thx

Date: Mon, 15 Jun 2015 07:09:59 -0700
