### ISSUE TITLE
Erorr LOGON FAILED

### ISSUE THREAD

**Issue by hakrawy** [ArielSaldana/Palringo-Bot-Engine#2]
Hello Mr Ariel

Is it possible to help me solve the following error

[](http://imgur.com/jip2HHy)
https://www.youtube.com/watch?v=dHz4eZ7m17o&feature=youtu.be
http://imgur.com/jip2HHy

You fill all the data correctly
- Tcp.cs
- public Tcp(string host = "80.69.129.117", int port = 12345)
- Program.cs
- Int32 port = 12345;
- settings.json
- "email": "***",
- "pass": "***"
  
  I do not know why it did not work bot
  😢

**Comment by ArielSaldana** [comment]
Could the username and password be incorrect? The bot seems to be working fine for me. 

I Suggest you create a new account and try it out.

**Comment by hakrawy** [comment]
Username and password is correct, I'm sure of it

**Comment by ArielSaldana** [comment]
Try 
IP : 80.69.129.123
PORT : 443,

Though... If your login info is correct I have no idea why the server would be sending back a "login failed" packet.

**Comment by hakrawy** [comment]
I do not know why ... but thank you

**Comment by ArielSaldana** [comment]
Can you fork the project and include all your changes for me to review?

Remember to exclude the setting files, as everyone will be able to see your private information.

**Comment by ArielSaldana** [comment]
Closing the issue, Reopen it if you're still having trouble.
